// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	Customerid  int32     `json:"customerid"`
	Email       string    `json:"email"`
	Name        string    `json:"name"`
	Street      string    `json:"street"`
	Postalcode  string    `json:"postalcode"`
	City        string    `json:"city"`
	Phonenumber string    `json:"phonenumber"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Meal struct {
	Mealid      int32          `json:"mealid"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	Category    string         `json:"category"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Order struct {
	Orderid     int32          `json:"orderid"`
	Customerid  int32          `json:"customerid"`
	Orderdate   time.Time      `json:"orderdate"`
	Totalamount pgtype.Numeric `json:"totalamount"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Orderdetail struct {
	Orderdetailid int32          `json:"orderdetailid"`
	Orderid       int32          `json:"orderid"`
	Mealid        int32          `json:"mealid"`
	Quantity      int32          `json:"quantity"`
	Price         pgtype.Numeric `json:"price"`
	CreatedAt     time.Time      `json:"created_at"`
}
